In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
[1,3,4,22,3.14]

[1, 3, 4, 22, 3.14]

In [5]:
#convert thành kiểu float 32 bit
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
a1=np.array([3,12,123])
type(a1)

numpy.ndarray

In [7]:
a2=np.array([[3,12,123],[123,21,1]])
type(a2)

numpy.ndarray

In [8]:
# a2 gồm 2 ồng, 3 cot
a2.shape

(2, 3)

In [9]:
a1.shape

(3,)

In [10]:
#tổng giá tr các phần tử của a2
a2.size

6

In [11]:
a2.dtype

dtype('int32')

In [12]:
#tạo hàm numpy array from scratch
#hàm tạo số 0
np.zeros([2,4],dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones([2,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
#mảng bắt đầu từ 0, đến 20, step = 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# chia khoảng cach tu 0 toi 1 chia thanh 5 doan
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#hàm random ra theo 4 dòng 4 ọot
np.random.random((4,4))

array([[0.9400726 , 0.69796935, 0.64435443, 0.01543892],
       [0.55216455, 0.35585557, 0.53065472, 0.0686734 ],
       [0.52767598, 0.95780896, 0.29895461, 0.05591143],
       [0.3700442 , 0.58969435, 0.74825855, 0.32969884]])

In [18]:
#np.random.normal(min,độ lệch chuẩn, (... dòng ... cột))
np.random.normal(0,1,(3,3))

array([[ 0.09403066,  1.39571674, -0.90818928],
       [ 2.48885748, -0.70874683,  1.34541849],
       [ 0.85094113, -1.69905086,  0.18632344]])

In [19]:
#random các số kiểu int (low, high, (;))

np.random.randint(4,10,(3,3))

array([[9, 9, 4],
       [7, 7, 8],
       [7, 8, 7]])

In [20]:
np.random.rand(4,3)

array([[0.45071198, 0.64161605, 0.03259666],
       [0.85401292, 0.43275796, 0.38886026],
       [0.92440066, 0.34095223, 0.69310976],
       [0.07039235, 0.39775872, 0.08520996]])

In [21]:
### array indexing & slicing
#random từ 0-20, với s lượng bằng 6
x1=np.random.randint(0,20,size=6)
print(x1)

[12  4  4 19 17 17]


In [22]:
#lấy phần tử số 4
x1[4]

17

In [23]:
x1[4],x1[0],x1[-1]

(17, 12, 17)

In [24]:
x2=np.random.randint(0,10,(3,4))
x2

array([[5, 9, 6, 6],
       [9, 9, 7, 2],
       [0, 4, 0, 2]])

In [25]:
x2[1,2]

7

In [26]:
x2[0,3]

6

In [27]:
#chọn hàng 2, cột 0, gán bang 5
x2[2,0]=5
x2

array([[5, 9, 6, 6],
       [9, 9, 7, 2],
       [5, 4, 0, 2]])

In [28]:
#slicing x[start:stop:step]
x1


array([12,  4,  4, 19, 17, 17])

In [29]:
x1[0:3 ]

array([12,  4,  4])

In [30]:
x1[0:5:2 ]

array([12,  4, 17])

In [31]:
x1[::2 ]

array([12,  4, 17])

In [32]:
x2


array([[5, 9, 6, 6],
       [9, 9, 7, 2],
       [5, 4, 0, 2]])

In [33]:
#lấy 2 dòng 3 cột
x2[:2,:3]

array([[5, 9, 6],
       [9, 9, 7]])

In [34]:
# lấy 2 cột đầu
x2[:,:2]

array([[5, 9],
       [9, 9],
       [5, 4]])

In [35]:
#reshaping and transpose
grid=np.arange(1,10)
grid.shape

(9,)

In [36]:
#chuyển thành bản 3x3
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
grid1=np.arange(1,9)
grid1.reshape(2,4).shape

(2, 4)

In [38]:
x=np.array([[1,4],[5,8]])
x

array([[1, 4],
       [5, 8]])

In [39]:
#transpose là đổi hành thành cột cột thành hang
x.T

array([[1, 5],
       [4, 8]])

In [40]:
#array concatenationg and splitting
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [41]:
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
#nối theo columm axis=1
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])

np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [45]:
#hàm nối chuỗi , gán 99 và chuỗi grid
y=np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [46]:
x=np.array([1,2,4,234,652,11,3])
np.split(x,[3,5])
#np.split(array,[tách từ v trí số 3 đến số 5])

[array([1, 2, 4]), array([234, 652]), array([11,  3])]

In [47]:
x1,x2,x3 =np.split(x,[3,5])


In [48]:
x1

array([1, 2, 4])

In [49]:
x2

array([234, 652])

In [56]:
a=np.arange(3)
a



array([0, 1, 2])

In [57]:
a+5
# = 0+5 ; 1+6; 2+5

array([5, 6, 7])

In [58]:
list_number=([1,2,3])
ll=np.array(list_number)
ll

array([1, 2, 3])

In [59]:
sum(ll)
#=1+2+3 python sum

6

In [60]:
#or numpysum
np.sum(ll)

6

In [61]:
massive_array=np.random.random(10000)
massive_array[:5]

array([0.47966422, 0.5746949 , 0.24795022, 0.8992732 , 0.5563978 ])

In [62]:
massive_array.shape

(10000,)

In [63]:
#so sánh thời gian python sum và np sum
%timeit sum(massive_array)
%timeit np.sum(massive_array)

829 µs ± 156 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
8.71 µs ± 847 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [64]:
sum(massive_array)

4979.605102960013

In [65]:
np.sum(massive_array)


4979.605102960032

In [66]:
#tính giá trị trung bình
np.mean(massive_array)

0.4979605102960032

In [67]:
np.max(massive_array)
#ớn nhất

0.9999131613133705

In [68]:
np.min(massive_array)

4.221227825584872e-05

In [69]:

#độ lệch chuân standard deviation
dog_height=([600,470,170,430,300])
dog_height=np.array(dog_height)

np.std(dog_height)
#công thức tính độ lệch chuẩn là căn bậc 2 của phương sa std.


147.32277488562318

In [72]:
#phương sai variant
np.var(dog_height)

21704.0

In [71]:
np.sqrt(np.var(dog_height))

147.32277488562318

In [73]:
#sorting array
x=np.array([2,1,4,123,12,1,5,6])
np.sort(x)

array([  1,   1,   2,   4,   5,   6,  12, 123])

In [74]:
#lấy ra vị trí của các biến vừa sort
np.argsort(x)

array([1, 5, 0, 2, 6, 7, 4, 3], dtype=int64)

In [76]:
#sorting along row and column
np.random.seed(42)
MatA=np.random.randint(0,10,size=(4,6))
MatA


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [77]:
np.sort(MatA,axis=0)
#sắp xếp theo cột

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [78]:
np.sort(MatA,axis=1)
#sắp xếp theo hàng

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [79]:
#linear algebra đại số tuyến tính
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[6,5],[4,3],[2,1]])


In [80]:
# A(3X3)dot B(3x2)
#tích vô hướng a với B
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [81]:
#hoặc
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [82]:
# nếu B(3x2) dot A(3x3) thì không được phải transpose
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [83]:
#DOT PRODUCT EXAMPLE
#Number of jars sold
np.random.seed(0)
sale_amount=np.random.randint(20,size=(5,3))
sale_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [84]:
import pandas as pd


In [85]:
weekly_sale=pd.DataFrame(sale_amount,index=['T2','T3','T4','T5','T6'],columns=['Bơ','Hạnh nhân','hủ bơ'])
weekly_sale

Bơ  Hạnh nhân  hủ bơ
T2  12         15      0
T3   3          3      7
T4   9         19     18
T5   4          6     12
T6   1          6      7

In [86]:
#tạo 1 chuỗi giá
price=np.array([10,8,12])

In [88]:
butter_prices=pd.DataFrame(price.reshape(1,3),index=["Price"],columns=['Bơ','Hạnh nhân','hủ bơ'])
butter_prices

Bơ  Hạnh nhân  hủ bơ
Price  10          8     12

In [91]:
total_price=weekly_sale.dot(butter_prices.T)
total_price

Price
T2    240
T3    138
T4    458
T5    232
T6    142

In [92]:
weekly_sale['Total Price']=total_price
weekly_sale

Bơ  Hạnh nhân  hủ bơ  Total Price
T2  12         15      0          240
T3   3          3      7          138
T4   9         19     18          458
T5   4          6     12          232
T6   1          6      7          142